# Generated by Django 4.2.5 on 2023-10-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='createdBy',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateField(),
        ),
    ]
